---

- name: Creates directory
  file:
    path: /home/ubuntu/backend/dist
    state: directory
    
- name: Copy files from project to backend server
  copy:
    src: /root/project/backend/dist
    dest: /home/ubuntu/backend/dist
