---

- name: Copy files from circleci to backend server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu/

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "tar"]
    state: latest
    update_cache: yes

- name: Install Node Dependencies
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Building backend service
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Running backend service
  shell: |
    cd /home/ubuntu/backend    
    pm2 start npm --no-automation --name "backend" -- run start
